apiVersion: apps/v1
kind: Deployment
metadata:
  name: xzlinuxpod-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: xzlinuxpod-operator
  template:
    metadata:
      labels:
        name: xzlinuxpod-operator
    spec:
      serviceAccountName: xzlinuxpod-operator
      containers:
        - name: xzlinuxpod-operator
          # Replace this with the built image name
          image: 192.168.22.36:5000/xzlinuxpod-operator
          command:
          - xzlinuxpod-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "xzlinuxpod-operator"
